                                                                                            THREAD PRIORITY
AIM:To write a Java program to demonstrate thread priority by assigning different priorities to multiple threads.
ALGORITHM:
Start the program.
Create three thread classes A, B, and C by extending the Thread class.
Override the run() method in each thread.
Create objects for threads A, B, and C.
Set thread C to maximum priority using Thread.MAX_PRIORITY.
Set thread A to minimum priority using Thread.MIN_PRIORITY.
Set thread B to a priority higher than thread A.
Start all three threads using the start() method.
Display the messages and values generated by each thread.
Display the end message from the main thread.
Stop the program.
PROGRAM:
class A extends Thread {
    public void run() {
        System.out.println("Thread A started");

        for (int i = 1; i <= 4; i++) {
            System.out.println("from thread A i = " + i);
        }

        System.out.println("exit from A");
    }
}

class B extends Thread {
    public void run() {
        System.out.println("Thread B started");

        for (int j = 1; j <= 4; j++) {
            System.out.println("from thread B j = " + j);
        }

        System.out.println("exit from B");
    }
}

class C extends Thread {
    public void run() {
        System.out.println("Thread C started");

        for (int k = 1; k <= 4; k++) {
            System.out.println("from thread C k = " + k);
        }

        System.out.println("exit from C");
    }
}

public class ThreadPriority {
    public static void main(String[] args) {

        A threadA = new A();
        B threadB = new B();
        C threadC = new C();

        // Set thread priorities
        threadC.setPriority(Thread.MAX_PRIORITY);
        threadB.setPriority(threadA.getPriority() + 1);
        threadA.setPriority(Thread.MIN_PRIORITY);

        System.out.println("Start thread A");
        threadA.start();

        System.out.println("Start thread B");
        threadB.start();

        System.out.println("Start thread C");
        threadC.start();

        System.out.println("End of main thread");
    }
}
OUTPUT:
Start thread A
Start thread B
Start thread C
End of main thread
Thread C started
from thread C k = 1
from thread C k = 2
from thread C k = 3
from thread C k = 4
exit from C
Thread B started
from thread B j = 1
from thread B j = 2
from thread B j = 3
from thread B j = 4
exit from B
Thread A started
from thread A i = 1
from thread A i = 2
from thread A i = 3
from thread A i = 4
exit from A

RESULT:
Thus, the Java program to demonstrate thread priority using multiple threads was successfully executed and the required output was obtained.
